name = "TaskmasterMPI"
uuid = "ec9ffb4d-f22d-40d8-9389-a9eaae758aa6"
authors = ["rstiskalek <richard.stiskalek@protonmail.com>"]
version = "0.1.0"

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
